// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Text = require("./../../output/Text");

function make(children) {
  return ReasonReact.wrapJsForReason(Text.text, /* () */0, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
